apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: argocd
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      name: tcp-8080
      targetPort: 8080
      protocol: TCP
    - port: 50000
      name: jnlpport
      targetPort: 50000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      # nodePort: 30007
